name    'puppet-openvpn'
version '0.3'
author 'arlimus'
license 'Apache 2.0'
summary 'OpenVPN server puppet module'
description 'Setup OpenVPN in puppet. Manage keys and certificates outside of puppet.'
